### ISSUE TITLE
startup should be faster

### ISSUE THREAD

**Issue by kylemcdonald** [ZigelbaumCoelho/ofxSick#4]
i think if you aren't changing the scan settings, then startup should be almost instant.

**Comment by I33N** [comment]
Is it really faster? I don't see the difference between LMS_FAST_RESTART or not.

It seems that commit 81240dd9f719b7cd303d3c5abc41cf104b991187 changed the fast startup.
Indeed line 234 in ofxSick.cpp:
laser.setScanCfg(targetCfg);
sets the config even if it is similar.

Is there a reason for going back to this?
